global using MediatR;
global using MassTransit;
global using Core.Domain.Models;
global using Routes;
global using Cargos;
global using Core.Domain.MessageBrokers;
global using Route.Application.Common.Interfaces;
global using Core.Domain.SagaInstances;
global using Route.GRPC.Client.Services;