global using Core.Application.Common.Interfaces;
global using Core.Application.Common.Models;
global using MassTransit;
global using MediatR;
global using Shipments;
global using Core.Domain.Models;
global using Core.Domain.MessageBrokers;
global using Enums;
global using Notifications;